# Generated by Django 3.2.7 on 2021-09-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_auto_20210924_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userpic',
            field=models.ImageField(blank=True, default='/media/none.png', upload_to='usr/%y'),
        ),
    ]
